---------------------Numerical Python: Numpy------------------------


In [1]:
import numpy as np

myarr=np.arange(1_000_000)
print(myarr)

mylist=list(range(1_000_000))
print(mylist[1:10])


#for same operation array took 3.86 ms while list took 180 ms sec time.
#Numpy has n dimensional array object or ndarray, which is fast flexible 
#container for large datasets in python.

[     0      1      2 ... 999997 999998 999999]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
%timeit myarr2=myarr*2

3.37 ms ± 350 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%timeit mylist2=mylist*2

27.9 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
data = np.array([[1.5, 0.1, 3],[0,-3,6.5]])
data

array([[ 1.5,  0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data.shape  # (rows, column)

(2, 3)

In [6]:
data.ndim

2

In [7]:
data*10

array([[ 15.,   1.,  30.],
       [  0., -30.,  65.]])

In [8]:
data+data


array([[ 3. ,  0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [9]:
data1=[6,7.5, 8.0, 1]
arr1= np.array(data1)
print(arr1)

[6.  7.5 8.  1. ]


In [10]:
arr1.ndim

1

In [11]:
np.zeros(10)  #an array of 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))   #make n dimensional matrix as given with all elements zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(15)   #arranging 0 to 14 in ascending order in a list/ array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)
print(arr)
float_arr = arr.astype(np.float64)  #explicit change in datatype of the elements in the array
print(float_arr.dtype)
print(float_arr)

int32
[1 2 3 4 5]
float64
[1. 2. 3. 4. 5.]


In [15]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [24]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr2= np.array([[0.,4.,1.],[7.,2.,12.]])

In [26]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [30]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

5

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr3=arr[5:8]
arr3

array([12, 12, 12])

In [37]:
arr3[1]=12345
arr3

array([   12, 12345,    12])

In [39]:
arr2d= np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
arr2d[2]

array([7, 8, 9])

In [41]:
arr2d[2][1]

8

In [43]:
arr2d[2,1]

8

In [45]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr= np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [51]:
arr= np.array([[0,1,0], [1,2,-2], [6,3,2], [-1,0,-1], [1,0,1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [54]:
print(arr.T)
np.dot(arr.T, arr)

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

-----------------------------------------PANDAS--------------------------------------------

In [56]:
#Series and Data frame

#series is one dimensional array like object containing a sequence of values

In [57]:
import pandas as pd

In [59]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [60]:
obj2 = pd.Series([4,7,-5,3],index=["d","b","a","c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [61]:
obj2["a"]

-5

In [63]:
obj2[["c","a","d"]]

c    3
a   -5
d    4
dtype: int64

In [65]:
obj2= pd.Series([4,7,-5,3,5], index=["d","b","a","a","c"])
obj2

d    4
b    7
a   -5
a    3
c    5
dtype: int64

In [67]:
obj2[obj2>3]

d    4
b    7
c    5
dtype: int64

In [68]:
obj2*2

d     8
b    14
a   -10
a     6
c    10
dtype: int64

In [70]:
import numpy as np 
np.exp(obj2)


d      54.598150
b    1096.633158
a       0.006738
a      20.085537
c     148.413159
dtype: float64

In [73]:
sdata = {"Ohio": 350000, "Texas": 71000, "Oregon":16000, "Utah":5000}
obj3=pd.Series(sdata)
obj3

Ohio      350000
Texas      71000
Oregon     16000
Utah        5000
dtype: int64

In [75]:
obj3.to_dict()

{'Ohio': 350000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [76]:
#Data frame has both a row index and column index


In [84]:
data = {"states": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
       "year":[2000, 2001, 2002, 2001, 2002, 2003],
       "pop": [1.5, 1.7, 3.6, 2.4,2.9, 3.2]}

frame= pd.DataFrame(data)
frame

states  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [85]:
frame.head()    #gives top  5 by default frame.head(n=?)

states  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [86]:
frame.tail()    #gives bottom  5 by default frame.head(n=?)

states  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [88]:
pd.DataFrame( data, columns=["year", "states", "pop"])

year  states  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [89]:
frame2 = pd.DataFrame(data, columns=["year", "states", "pop", "debt"])
frame2

year  states  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [90]:
frame2.columns

Index(['year', 'states', 'pop', 'debt'], dtype='object')

In [91]:
frame2["states"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: states, dtype: object

In [92]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [93]:
frame2[["states", "year"]]

states  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [94]:
frame2.loc[1]

year      2001
states    Ohio
pop        1.7
debt       NaN
Name: 1, dtype: object

In [97]:
frame2.iloc[2]

year      2002
states    Ohio
pop        3.6
debt       NaN
Name: 2, dtype: object

In [98]:
#difference between iloc[] and loc[] : https://www.geeksforgeeks.org/difference-between-loc-and-iloc-in-pandas-dataframe/

In [100]:
frame2["debt"]=16.5
frame2

year  states  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [102]:
frame2["debt"]=np.arange(6.)
frame2

year  states  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [103]:
frame2["eastern"]=frame2["states"]=="Ohio"
frame2

year  states  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [104]:
del frame2["eastern"]
frame2.columns

Index(['year', 'states', 'pop', 'debt'], dtype='object')